### ISSUE TITLE
Check stage duration calculations

### ISSUE THREAD

**Issue by tdjames1** [Ellie7/parrot-proj#14]
Stage duration in days should be divided by 365, not 356?
Age 13-36 months is inclusive so I think it should be 24/12.
Where does 7 come from?

https://github.com/Ellie7/parrot-proj/blob/572dc61e6ca879c044a7ff71bf3d551abb94585d/YSA%20demography.R#L22

**Comment by Ellie7** [comment]
Thank you for spotting those! 
7 was from somewhere where I read the median or mean of ysa's age was 10, so 7 was 10 - the 36 months. Is there a more accurate adult stage duration you would recommend for now?

**Comment by tdjames1** [comment]
I'm not sure  - @andbeck, what do you think? (The stage duration is needed to calculate the matrix entries following Crouse's method.)

@Ellie7, it would be good if you could track down the "somewhere" you read that so that you can back it up in your report.

**Comment by andbeck** [comment]
So we are looking for some data on lifespan?

http://www.life.umd.edu/faculty/wilkinson/South&Wilk05.pdf

Not sure about the 10/7 number.  I think a good idea is to think about the adult survival values and how 1/lifespan = rough estimate of survival.  Also, take the captive detail as a massive upper limit.

Is there anything in Sam/Rowan thesis?

**Comment by andbeck** [comment]
And in a pinch - look at the excel database we have for averages for the amazons...

I do think that tamora's estimation of survival and then assuming 1/longegity = survival rate will be a good way to go...

**Comment by tdjames1** [comment]
@Ellie7 Take another look at the first three entries - they should add up to one year, right?
`(27/365) + (59/365) + (270/365) = ?`

I think that's why you've got a negative number in your matrix.

https://github.com/Ellie7/parrot-proj/blob/3277ef84fa94b540d948a47afde5029d951e61d2/YSA%20demography.R#L22

**Comment by Ellie7** [comment]
have corrected the bad maths (I hope)!

**Comment by tdjames1** [comment]
Fixed with commit 170c2765504e
