### ISSUE TITLE
Halve fecundity estimate

### ISSUE THREAD

**Issue by tdjames1** [Ellie7/parrot-proj#15]
I think you're right about this - the model is for females only, so the mean number of offspring should be halved (assuming 1:1 sex ratio).

https://github.com/Ellie7/parrot-proj/blob/3277ef84fa94b540d948a47afde5029d951e61d2/YSA%20demography.R#L26

cc @andbeck

**Comment by Ellie7** [comment]
Have halved it now :)

**Comment by Ellie7** [comment]
fixed with commit fc2760a

**Comment by tdjames1** [comment]
N.B. I think that the SD should be halved as well.

**Comment by Ellie7** [comment]
thank you, that was very dopey of me not to change that too, fixed with commit c4fd87e
