### ISSUE TITLE
Don't round elasiticity values

### ISSUE THREAD

**Issue by tdjames1** [Ellie7/parrot-proj#16]
You don't need to do this. Just plot the raw values.
https://github.com/Ellie7/parrot-proj/blob/170c2765504e027b45878ef5e6332a1efea0d235/YSA%20demography.R#L194

**Comment by tdjames1** [comment]
I see you've taken out that line, but does your plotting code work now? ;)

**Comment by Ellie7** [comment]
no aha thank you!

**Comment by Ellie7** [comment]
fixed with commit 711e306
