### ISSUE TITLE
Amend matrix calculations to correct versions

### ISSUE THREAD

**Issue by tdjames1** [Ellie7/parrot-proj#17]
The 0.99 workaround that you've used in these lines:

https://github.com/Ellie7/parrot-proj/blob/711e30676695c3a46a7823ee0d787233e4acd6aa/ysa%20functions.R#L51
https://github.com/Ellie7/parrot-proj/blob/711e30676695c3a46a7823ee0d787233e4acd6aa/ysa%20functions.R#L98

should no longer be necessary now that you've fixed the stage durations (#14).

**Comment by Ellie7** [comment]
fixed with commit  b6223f3
