### ISSUE TITLE
YSA functions script should only contain functions!

### ISSUE THREAD

**Issue by tdjames1** [Ellie7/parrot-proj#18]
Lines 5-15 are surplus to requirements - I would remove them to avoid confusion with the data structures you're creating in your main script.

**Comment by tdjames1** [comment]
You can close this issue now! A good practise is to add a comment which indicates the commit ID (in this case 9ef9aaa21) that fixes the issue and then close it.

**Comment by Ellie7** [comment]
Thank you Tamora will do in future :)

**Comment by tdjames1** [comment]
I spoke too soon (i.e. I didn't test it) - you need to get rid of the call to ysaFunc(), too (line 55).

**Comment by Ellie7** [comment]
just realised too! sorted now :)
