### ISSUE TITLE
Crouse's matrix 

### ISSUE THREAD

**Issue by Ellie7** [Ellie7/parrot-proj#2]
@andbeck @tdjames1
weirdly, when I added the di^-1 in line 23  di^-1 the Pi values were further from those in Crouses matrix and without the ^-1 they are closer to those in Crouses paper so I don't know if there's a problem with how I calculated the di and pi's initially or the formulae I entered to calculate Pi
my r code: 
`#Fs
fecs <- select(table.3, fecundity)

pi <- select(table.3, annual_survivorship)
di <-select(table.3, stage_duration)
#Ps
Pi <- ((1-(pi^di))/(1-(pi^di)))*pi #original we looked at on Monday
Pi <- (1-(pi^di^-1))/(1-(pi^di))*pi #amended now produces a weirder output 
#Gs
Gi <- ((pi^di)*(1-pi))/(1-(pi^di)) 
Gi <- round(Gi, 4)`

**Comment by Ellie7** [comment]
I think I've put the CSV file for the table 3 data on here (in the Crouse script), sorry if doesn't work!

**Comment by tdjames1** [comment]
Hi Ellie, try `1 - pi^(di-1)` (and look up operator precedence in R!)

**Comment by Ellie7** [comment]
Hi Tamora, I've just tried that and it's still not happy :/ and will do! thank you 

all sorted now!

**Comment by tdjames1** [comment]
👍 You can close the issue if you've got it sorted!

**Comment by Ellie7** [comment]
Not as sorted as I would've had liked, just realised that my pi values are slightly off Crouse's:
#P1              0.0000
#P2              0.7198 (Crouse = 0.7370)
#P3              0.6535 (Crouse = 0.6610)
#P4              0.6675 (Crouse = 0.6907)
#P5              0.0000
#P6              0.0000
#P7              0.8086 (Crouse = 0.8089)
I don't know if they are right or not as they are very close to Crouse's?

**Comment by tdjames1** [comment]
Hi Ellie, I think this is a problem with your stage durations. Think of the ranges in the Crouse Table 3 as inclusive, i.e. 1-7 means 1, 2, 3, 4, 5, 6, 7 => 7 years in total.
