### ISSUE TITLE
YSA LSA script - 1000 simulations wrecks the sensitivity plot 

### ISSUE THREAD

**Issue by Ellie7** [Ellie7/parrot-proj#26]
changing from 100 to 1000 simulations ruins the mean sensitivity plot, however, if I can get the other sensitivity plot (to 10% changes) this might not matter as this plot is a bit redundant anyway?

**Comment by tdjames1** [comment]
What do you mean by "ruins"? :)

**Comment by Ellie7** [comment]
It makes the G2 column crazy big (in the thousands) and the rest really small in comparison

**Comment by tdjames1** [comment]
Sometimes `ysaFunc()` creates matrices which are ill-conditioned, here's one where for some reason the values for P2, G2 and P3 are very close to zero. The eigen analysis produces a crazy sensitivity value for G2 and that's what's messing up your plots.

```
> mat1$M86
          col1      col2     col3
row1 0.0000000 0.000e+00 1.526923
row2 0.3153555 9.999e-05 0.000000
row3 0.0000000 9.999e-09 0.000100

> eigen.analysis(mat1$M86)$sensitivities
            col1         col2         col3
row1 0.000000000 0.000000e+00 0.0003684865
row2 0.001784178 3.397823e-01 0.0000000000
row3 0.000000000 5.627066e+04 0.3397843368
> 
```

There are a couple of stages to working around this in your YSA LSA script.
1. Only carry out eigen analysis if the matrix is well-behaved. We do this using the `condest` function from the `Matrix` package:
```
# use map and eigen.analysis
out <- map(mat1, function(m) {
  if (Matrix::condest(m)$est > 100) {
    NULL
  } else {
    eigen.analysis(m)
  }
}) 
```
2. Modify data frame creation to deal with NULLs in `out`:
```
# create a data frame where columns are the matrix ID and rows are the elements
# of the sensitivity matrix
out2s <- map_df(out, function(x) { if(!is.null(x)) { cbind(c(x$sensitivities)) } else { matrix(rep(NA, 9)) } }) 
```
3. Modify calculations of mean/se sensitivity to handle NAs in `out2s` (by using `na.rm = TRUE` when calculating mean/SE)
```
se_fnc <- function(x){sd(x, na.rm = TRUE)/sqrt(sum(!is.na(x)))}

# these are the mean and se matrices of sensitivity, in this case.
mean_sensitivity <- matrix(rowMeans(out2s, na.rm = TRUE),3,3,
                           dimnames = list(use.names.r,use.names.c))
se_sensitivity <- matrix(apply(out2s, 1, function(x) se_fnc(x)), 3,3)
```
Let me know if it works!

**Comment by tdjames1** [comment]
Going back to why this is happening at all, the problem seems to be because we’re passing in quite a high variance/SD to the function that generates values from the beta distribution - try calling `betaval(0.852, 0.3451, fx = runif(1))` repeatedly - most of the numbers output are around 0.99 (unrealistically high for survival estimate) and occasionally there is a 1e-04 which results in an ill-conditioned matrix.

Should we just ignore the variance generated from the imputation and use a value for SD that results in beta values in a sensible range around the mean? e.g. in the initial life table we were using SD of  0.075.

**Comment by Ellie7** [comment]
just running it now

**Comment by Ellie7** [comment]
sorry for the slow reply, was focusing on slack and didn't realise this was going on on here!

**Comment by Ellie7** [comment]
I'm getting an error for 2, as now the row & column names aren't coming out, just come out as NULL 
which means this line `out2s <- map_df(out, function(x) { if(!is.null(x)) { cbind(c(x$sensitivities)) } else { matrix(rep(NA, 9)) } })` isn't working

**Comment by tdjames1** [comment]
OK, sounds like the first matrix in your output was broken so it's just given you back NULL. Try generating mat1 again.

Sorry about this, it might be worth waiting until I'll figured out if I can generate a corrected variance for the survival estimate...

**Comment by Ellie7** [comment]
will do :)

No worries, I'll try to get on with some writing for a bit while stuff gets
figured out. Thank you for all your help.

**Comment by Ellie7** [comment]
@tdjames1  should I take out these modifications from the script now we've got the new smaller SD value?

**Comment by tdjames1** [comment]
Yes - hopefully if you put in the corrected estimate of SD things will work and you won't need the changes above.

**Comment by Ellie7** [comment]
Done and run it all and all working!!!
