### ISSUE TITLE
Don't round numbers to be used in further calculations

### ISSUE THREAD

**Issue by tdjames1** [Ellie7/parrot-proj#3]
When calculating the projection matrix entries you have rounded the values and reassigned them back to the vector like this:

     Pi <- round(Pi, 4)

I understand that you want to see the numbers in the same format as in the paper. The problem is that by doing this you're throwing away information and that can affect further calculations.

You can use `print` like this:

    print(Pi, digits = 4)

to view the values of the vector with a given number of decimal digits.

**Comment by Ellie7** [comment]
ahh thank you that's really helpful! I hadn't thought that it I was rounding the numbers in the matrix not just when printing it!
