### ISSUE TITLE
Eigen analysis results 

### ISSUE THREAD

**Issue by Ellie7** [Ellie7/parrot-proj#6]
@andbeck @tdjames1
Despite the matrix I made for figure 1 (with the fecundity and survivorship being reduced by 50%) matching the one given in the Crouse paper appendix, the eigen values that come out are very different.  
Can't work out why the eigen values would be wrong when the matrix is wrong and the code is so simple.. I'm probably being really silly!

**Comment by andbeck** [comment]
Maybe I've missed something, but

a) don't do this: lifetable <- lifetable.3; just use myFunc(lifetable.3)

your function names whatever you give it, lifetable.

b) why do you have this in the function?  After you make the matrix, just assign the values to rows and cells, as you did in the long form....?

  for (i in 2:7) {
    for (j in 2:7) mat1[i, j]

Hmm.... ;-)

**Comment by Ellie7** [comment]
all very true and have updated my script accordingly! but it still produces the weird values from the eigenanalysis which don't match up with lambdas in Crouse's paper (in the appendix) :/

**Comment by tdjames1** [comment]
Ellie, have another read through the first couple of paragraphs in the "Sensitivity analysis" section of the paper. Can you see the difference between what you've done and the method they used? Clue: _you need more than two eigen analyses to get all of the results needed to recreate the figure._

By the way, regarding the new life tables that you've made with increased and decreased values for survival and fecundity... A better approach would be create a copy of your original life table and then use R to manipulate the values you want to change. That way everything you've done is within your script and is reproducible.
