### ISSUE TITLE
Use file paths that are relative to the project directory

### ISSUE THREAD

**Issue by tdjames1** [Ellie7/parrot-proj#7]
Hi Ellie, in calls to `read.csv()`, please use relative file paths e.g 

    read.csv("sens.csv")

instead of

    read.csv("~/1 UNIVERSITY/Level 4/Project & Dissertation/Crouse 1987/sens.csv")

That way it'll work for Andrew and me even though we don't have the same filing system as you (as long as we've set our working directory to the project directory or are working in an Rstudio project).

**Comment by Ellie7** [comment]
Will do :) thank you!
